-- =====================================================
-- Migración: Tablas del Modo Party
-- Fecha: 2025-12-31
-- Descripción: Crea tablas para el sistema de aula virtual multiplayer
-- =====================================================

-- Tabla principal de parties (sesiones de examen grupal)
CREATE TABLE IF NOT EXISTS public.parties (
  id TEXT PRIMARY KEY,
  pin TEXT UNIQUE NOT NULL,
  host_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  status TEXT DEFAULT 'waiting' CHECK (status IN ('waiting', 'active', 'paused', 'finished')),
  config JSONB, -- Almacena PartyConfig completo
  total_questions INTEGER DEFAULT 20,
  ai_analysis TEXT, -- Análisis generado por Gemini AI
  created_at TIMESTAMPTZ DEFAULT NOW(),
  started_at TIMESTAMPTZ,
  ended_at TIMESTAMPTZ
);

-- Índices para búsquedas rápidas
CREATE INDEX IF NOT EXISTS idx_parties_pin ON public.parties(pin);
CREATE INDEX IF NOT EXISTS idx_parties_host ON public.parties(host_id);
CREATE INDEX IF NOT EXISTS idx_parties_status ON public.parties(status);

-- Tabla de jugadores por party
CREATE TABLE IF NOT EXISTS public.party_players (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  party_id TEXT REFERENCES public.parties(id) ON DELETE CASCADE,
  player_id TEXT NOT NULL,
  nickname TEXT NOT NULL,
  score INTEGER DEFAULT 0,
  rank INTEGER,
  correct_answers INTEGER DEFAULT 0,
  total_answers INTEGER DEFAULT 0,
  average_time_ms INTEGER DEFAULT 0,
  suspicious_events INTEGER DEFAULT 0,
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  finished_at TIMESTAMPTZ
);

-- Índices para party_players
CREATE INDEX IF NOT EXISTS idx_party_players_party ON public.party_players(party_id);
CREATE INDEX IF NOT EXISTS idx_party_players_score ON public.party_players(score DESC);

-- =====================================================
-- Row Level Security (RLS)
-- =====================================================

ALTER TABLE public.parties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.party_players ENABLE ROW LEVEL SECURITY;

-- Policies para parties
-- Permitir lectura pública de parties activas (para unirse)
CREATE POLICY "Allow public read active parties" ON public.parties
  FOR SELECT
  USING (status IN ('waiting', 'active'));

-- Permitir al host gestionar su propia party
CREATE POLICY "Allow host full access to own party" ON public.parties
  FOR ALL
  USING (auth.uid() = host_id);

-- Permitir insertar parties (usuarios autenticados)
CREATE POLICY "Allow authenticated users to create parties" ON public.parties
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = host_id);

-- Policies para party_players
-- Permitir lectura pública de jugadores
CREATE POLICY "Allow public read players" ON public.party_players
  FOR SELECT
  USING (true);

-- Permitir insertar jugadores (cualquiera puede unirse)
CREATE POLICY "Allow anyone to join party" ON public.party_players
  FOR INSERT
  WITH CHECK (true);

-- Permitir actualizar score (service role only, via edge functions)
CREATE POLICY "Allow service role to update players" ON public.party_players
  FOR UPDATE
  USING (true);
