-- =====================================================
-- Migración: Tabla party_sessions
-- Fecha: 2025-12-31
-- Descripción: Crea tabla party_sessions para el modo party
-- Nota: Los componentes PartyHost.svelte y PartyJoin.svelte usan esta tabla
-- =====================================================

-- Tabla de sesiones de party (exámenes grupales en tiempo real)
CREATE TABLE IF NOT EXISTS public.party_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  party_code TEXT UNIQUE NOT NULL,
  host_name TEXT NOT NULL DEFAULT 'Host',
  exam_config JSONB DEFAULT '{}'::jsonb,
  students JSONB DEFAULT '[]'::jsonb,
  max_students INTEGER DEFAULT 10,
  status TEXT DEFAULT 'waiting' CHECK (status IN ('waiting', 'active', 'paused', 'finished')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  started_at TIMESTAMPTZ,
  ended_at TIMESTAMPTZ
);

-- Índices para búsquedas rápidas
CREATE INDEX IF NOT EXISTS idx_party_sessions_code ON public.party_sessions(party_code);
CREATE INDEX IF NOT EXISTS idx_party_sessions_status ON public.party_sessions(status);

-- =====================================================
-- Row Level Security (RLS)
-- =====================================================

ALTER TABLE public.party_sessions ENABLE ROW LEVEL SECURITY;

-- Permitir lectura pública de parties activas (para unirse)
CREATE POLICY "Allow public read party_sessions" ON public.party_sessions
  FOR SELECT
  USING (status IN ('waiting', 'active'));

-- Permitir insertar parties (cualquiera puede crear)
CREATE POLICY "Allow public insert party_sessions" ON public.party_sessions
  FOR INSERT
  WITH CHECK (true);

-- Permitir actualizar parties (para agregar estudiantes)
CREATE POLICY "Allow public update party_sessions" ON public.party_sessions
  FOR UPDATE
  USING (true);
