name = "worldexams-api"
main = "src/index.ts"
compatibility_date = "2026-03-10"
workers_dev = false

[vars]
SUPABASE_URL = "https://tzmrgvtptdtsjcugwqyq.supabase.co"

[[routes]]
pattern = "api.saberparatodos.space"
custom_domain = true
