-- Create table for exam results
create table public.exam_results (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_name text not null,
  score integer not null,
  total_questions integer not null,
  subject text not null,
  percentage integer generated always as ((score::float / total_questions::float) * 100) stored
);

-- Enable Row Level Security (RLS)
alter table public.exam_results enable row level security;

-- Create policy to allow anyone to insert results (for now, can be restricted later)
create policy "Allow public inserts"
on public.exam_results
for insert
to public
with check (true);

-- Create policy to allow anyone to read results
create policy "Allow public read"
on public.exam_results
for select
to public
using (true);

-- =====================================================
-- WORLD EXAMS - INSTITUTIONAL SYSTEM
-- Added: 2026-02-19
-- =====================================================

-- Table: colleges (Todos los colegios de Colombia)
create table public.colleges (
  id uuid primary key default gen_random_uuid(),
  cod_dane varchar(20) unique not null,
  name varchar(255) not null,
  department varchar(100),
  municipality varchar(100),
  sector varchar(20),
  character varchar(50),
  calendar varchar(20),
  address varchar(255),
  phone varchar(50),
  email varchar(255),
  principal varchar(255),
  total_students integer,
  created_at timestamptz default now()
);

create index idx_colleges_department on colleges(department);
create index idx_colleges_municipality on colleges(municipality);
create index idx_colleges_name on colleges(name);

-- Enable RLS
alter table public.colleges enable row level security;
create policy "Allow public read colleges" on public.colleges for select to public using (true);

-- Table: organization_students (Vinculación estudiantes-organizaciones)
create table public.organization_students (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid references organizations(id) on delete cascade,
  student_id varchar(50) not null,
  student_name varchar(255),
  grade varchar(10),
  section varchar(5),
  joined_at timestamptz default now(),
  unique(organization_id, student_id)
);

create index idx_org_students_org on organization_students(organization_id);

-- Enable RLS
alter table public.organization_students enable row level security;
create policy "Org members can read students" on organization_students for select to public using (true);
create policy "Org members can insert students" on organization_students for insert to public with check (true);

-- Table: organization_groups (Grupos/Clases)
create table public.organization_groups (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid references organizations(id) on delete cascade,
  name varchar(100) not null,
  grade varchar(10),
  section varchar(5),
  created_at timestamptz default now()
);

create index idx_org_groups_org on organization_groups(organization_id);

-- Enable RLS
alter table public.organization_groups enable row level security;
create policy "Org members can read groups" on organization_groups for select to public using (true);
create policy "Org members can insert groups" on organization_groups for insert to public with check (true);

-- Add invite_code to organizations
alter table organizations add column invite_code varchar(10) unique;
